### ISSUE TITLE
Uncaught ReferenceError: Button is not defined

### ISSUE THREAD

**Issue by timscott** [otissv/react-uikit-button-group#1]
I followed the example in README exactly and I get:

```
Uncaught ReferenceError: Button is not defined
```

I'm somewhat new to React so apologies if I'm doing something stupid. I'm using [react_on_rails](https://github.com/shakacode/react_on_rails).

**Comment by otissv** [comment]
The Button as well as the ButtonGroup needs to be imported, which the README is missing.

```
npm install react-uikit-button --save;

// ES6
import Button from 'react-uikit-button';

// ES5
var Button = require('react-uikit-button');
```

I'll update the README.

Let me know if that helped?

**Comment by timscott** [comment]
Yes, that was it. Thanks!
